### ISSUE TITLE
Display the Proxy URL value

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/invite-anyone#1]
Everyone will need to paste this URL into their CloudSponge account settings, so let's make it easy to copy it to their clipboard and deep link directly to the page where they need to paste it.

**Comment by dimitarangelkov** [comment]
There is no proxy file at all, started working on this upgrade.

Branch
https://github.com/cloudsponge/invite-anyone/tree/cloudsponge-proxy

**Comment by circuitfive** [comment]
Any page that has our script on it can be used as a proxy url. The proxy file does not need to be included. Please discuss the best approach with @dangerouse before spending any more time on it.

**Comment by dimitarangelkov** [comment]
for this implementation we need a dedicated proxy page, since the CS script is displayed in dynamic pages on the front-end, the "members" pages.

**Comment by dimitarangelkov** [comment]
![Screenshot 2020-10-23 at 11 40 13](https://user-images.githubusercontent.com/14825668/96976465-8dfb6180-1524-11eb-86c0-ea3600de0230.png)

**Comment by dimitarangelkov** [comment]
![Screenshot 2020-11-27 at 11 37 57](https://user-images.githubusercontent.com/14825668/100434560-55abed80-30a5-11eb-9259-8abeea29ecc9.png)

**Comment by circuitfive** [comment]
LGTM
