### ISSUE TITLE
Error displayed inside the "CloudSponge Key" field

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/invite-anyone#12]
![image.png](https://images.zenhubusercontent.com/5893c7ec51aa2c3057736077/39673f07-66b0-4b10-9221-3c216930b6be)

**Comment by dimitarangelkov** [comment]
@dangerouse the fix itself is trivial, unfortunately I am not sure how to sync the fork that we have in our repo with the original one, so we can apply the fix against the latest codebase and avoid promoting code that is not currently in use.

**Comment by dangerouse** [comment]
hey @dimitarangelkov you should open the PR against this branch that appears to be the one that Boone is using for the current version of Invite Anyone: https://github.com/cloudsponge/invite-anyone/tree/1.4.x

Switch to the `1.4.x` branch and commit your change there please. Then you can open a PR with only 1 change.

**Comment by dimitarangelkov** [comment]
@dangerouse https://github.com/boonebgorges/invite-anyone/pull/170 done
