### ISSUE TITLE
Copy changes to the "CloudSponge" settings panel

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/invite-anyone#2]
![image](https://user-images.githubusercontent.com/2659746/94882769-bad4c100-041d-11eb-8f7d-71a102ff10aa.png)

This area needs some visualizations of our contact picker. A CloudSponge logo and a link to our sign up page are not very useful for anyone who has not heard of us.

Also, consider renaming the tab from "CloudSponge" to "Contact Picker"

**Comment by dimitarangelkov** [comment]
hey @circuitfive let me know if you still prefer to make those changes with the current PR or we can move them to a separate one.

**Comment by circuitfive** [comment]
@dimitarangelkov go ahead and do the following:

* [x] Change the label on the "CloudSponge" tab with "Contact Picker"
* [x] Update the logo image to our current logo (without the flare and shadow)
* [ ] Consider updating the `invite_anyone.pot` file so that the `msgid` is more abstract, the way it's currently set up doesn't look right to me. Once this is structured properly it will be easier for me to update this copy in the future and get translations done.
* [ ] Remove the "CloudSponge" heading.
* [x] Replace the paragraph with the following:

>Every successful social network has one thing in common: a contact picker. It's the proven way to grow your network virally because it's the best interface for your users to input a long list of email addresses into your invitation form. Without a contact picker, your users will have to type emails into your invitation form manually or copy and paste them from another window.
>
>Invite Anyone's integration with CloudSponge's Contact Picker plugs all of the popular webmail address book providers into your BuddyPress-powered website instantly. Your users will be able to select and input all of their friends' email addresses directly from Google Contacts, Yahoo Mail, Outlook.com, Office 365, AOL, iCloud, and dozens more around the world.
>
>Here's how:
>1. [Create a CloudSponge account to get your API key](https://www.cloudsponge.com/signup/invite-anyone/)
>2. Paste your API key here in your Invite Anyone settings below
>3. Follow the setup instructions provided by CloudSponge
>4. [Contact the CloudSponge team](https://www.cloudsponge.com/contact/) if you have any questions

* [x] Please make sure that all hyperlinks are https and they include Invite Anyone referral partner parameters.

**Comment by dimitarangelkov** [comment]
@circuitfive you can have a quick look using the `master` branch.

I'll ask Boone Georges how to proceed with the translation files and if we have to update them with the latest changes or this is something he will take care of. As for the translation keys, I know what you mean, unfortunately the concept here is a bit different https://developer.wordpress.org/reference/functions/_e/ , and if I add abstraction keys for the translations for the CloudSponge tab of the plugin will be inconsistent with the rest of the plugin.   

Regarding the heading title, I am afraid it is part of the general layout, so will have to keep it.

![Screenshot 2021-02-02 at 19 21 51](https://user-images.githubusercontent.com/14825668/106637966-01812600-658c-11eb-81a5-3817b963b0e2.png)

Let me know if I can request a review from Boone.

**Comment by circuitfive** [comment]
Thanks @dimitarangelkov your screenshot looks great, let's submit to @boonebgorges to get his reaction.

**Comment by dangerouse** [comment]
LGTM 👍
