### ISSUE TITLE
Add an option to enable deep links

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/invite-anyone#3]
![image](https://user-images.githubusercontent.com/2659746/94882904-17d07700-041e-11eb-8274-65468769e21e.png)

The "from your Address Book" link is a good default, but people should be able to override it and show address book logos here instead.

https://www.cloudsponge.com/developer/contact-picker/linking-options/deep-links/

**Comment by dimitarangelkov** [comment]
This feature extends #4

![Screenshot 2020-11-27 at 20 39 54](https://user-images.githubusercontent.com/14825668/100477418-f7a4f780-30f0-11eb-8e8d-0e6d77d7abce.png)

![Screenshot 2020-11-27 at 20 40 06](https://user-images.githubusercontent.com/14825668/100477436-012e5f80-30f1-11eb-91e9-0ea94521fc3a.png)
