### ISSUE TITLE
Allow users to enable only the address book providers that they want

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/invite-anyone#4]
Our contact picker's menu can easily be customized with our `sources` option: https://www.cloudsponge.com/developer/contact-picker/options/sources/

We're already setting it here:
https://github.com/cloudsponge/invite-anyone/blob/33cf20f114641e9ca7fbaa5fbde4190b8131b065/by-email/cloudsponge-js.js#L11

So maybe we can easily make this dynamic.

**Comment by boonebgorges** [comment]
Does the CloudSponge API have a way of fetching all supported `sources`? I see them listed on https://www.cloudsponge.com/developer/contact-picker/options/sources/ but it would be ideal to fetch them dynamically, in case they change.

**Comment by circuitfive** [comment]
It does not, but that's not a bad idea! cc @dangerouse

**Comment by dimitarangelkov** [comment]
This is ready for review in `configurable-sources` branch.

### Sample 1
![Screenshot 2020-11-27 at 16 21 46](https://user-images.githubusercontent.com/14825668/100458559-ab47c080-30cc-11eb-9816-41f08a5bae24.png)

![Screenshot 2020-11-27 at 16 22 17](https://user-images.githubusercontent.com/14825668/100458614-bbf83680-30cc-11eb-8b97-0b643fc03c21.png)

### Sample 2
![Screenshot 2020-11-27 at 16 23 00](https://user-images.githubusercontent.com/14825668/100458714-e3e79a00-30cc-11eb-9be1-2e11cc27be47.png)

![Screenshot 2020-11-27 at 16 23 20](https://user-images.githubusercontent.com/14825668/100458720-e6e28a80-30cc-11eb-8b84-e58ae08ac158.png)

**Comment by dangerouse** [comment]
This endpoint https://api.cloudsponge.com/services.json returns a list of our sources and their statuses.

**Comment by dimitarangelkov** [comment]
@dangerouse I think would be better to create a new one, that will return all the sources with their keys and full names, also would be useful if we have URLs for each source default icon, so we can have it for the deep links feature on Invite-Anyone plugin

**Comment by dangerouse** [comment]
@dimitarangelkov check it out here: https://api.cloudsponge.com/services.json
